var loadingGame = '超级玛莉.nes';
var gamelist = [
    {name:"180_梦的探险者.nes",desc:"梦之探险者",img:"梦的探险者.png"},
    {name:"坦克大战.nes",desc:"坦克大战",img:"default.jpg"},
    {name:"雪人兄弟.NES",desc:"雪人兄弟",img:"default.jpg"},
    {name:"Kero Kero Keroppi no Daibouken 2 - Donuts Ike ha Oosawagi! (Japan).nes",desc:"大眼蛙",img:"default.jpg"},
    {name:"古巴英雄.nes",desc:"古巴英雄",img:"default.jpg"},

    {name:"超级玛莉.nes",desc:"超级玛莉",img:"mario.jpg"},
    {name:"超级马莉欧兄弟3(v20090423)[Nokoh汉化].nes",desc:"超级玛丽3",img:"default.jpg"},

    {name:"松鼠1.nes",desc:"松鼠1",img:"default.jpg"},
    {name:"松鼠2.nes",desc:"松鼠2",img:"default.jpg"},

    {name:"215_热血新纪录.nes",desc:"热血新纪录",img:"default.jpg"},
    {name:"热血物语[AIR汉化].nes",desc:"热血物语",img:"default.jpg"},
    {name:"热血篮球(v0.9)[AXI&AHE汉化].nes",desc:"热血篮球",img:"default.jpg"},

    {name:"冒险岛.nes",desc:"冒险岛",img:"default.jpg"},
    {name:"冒险岛2 [Nokoh汉化].nes",desc:"冒险岛2",img:"default.jpg"},
    {name:"冒险岛3(v20110101)[Nokoh汉化].nes",desc:"冒险岛3",img:"default.jpg"},
    {name:"冒险岛4.nes",desc:"冒险岛4",img:"default.jpg"},

    {name:"洛克人.nes",desc:"洛克人",img:"default.jpg"},
    {name:"洛克人2[NeoX汉化].nes",desc:"洛克人2",img:"default.jpg"},
    {name:"洛克人3 - Dr.Wily的末日 [MS汉化].nes",desc:"洛克人3",img:"default.jpg"},
    {name:"洛克人4-新的野心[MS汉化].nes",desc:"洛克人4",img:"default.jpg"},
    {name:"洛克人5-布鲁斯的圈套[MS汉化].nes",desc:"洛克人5",img:"default.jpg"},
    {name:"洛克人6-史上最长的战斗[MS汉化].nes",desc:"洛克人6",img:"default.jpg"},

    // {name:"魂斗罗1 (U)30.nes",desc:"魂斗罗1",img:"default.jpg"},
    // {name:"魂斗罗1 (U)30F.nes",desc:"魂斗罗1-F弹药",img:"default.jpg"},
    // {name:"魂斗罗1 (U)30L.nes",desc:"魂斗罗1-L弹药",img:"default.jpg"},
    // {name:"魂斗罗1 (U)30M.nes",desc:"魂斗罗1-M弹药",img:"default.jpg"},
    {name:"魂斗罗1 (U)30S.nes",desc:"魂斗罗",img:"default.jpg"},
    {name:"魂斗罗2 (U)30S.nes",desc:"超级魂斗罗",img:"default.jpg"},


    {name:"忍者神龟2.nes",desc:"忍者神龟2",img:"default.jpg"},
    {name:"忍者神龟3.nes",desc:"忍者神龟3",img:"default.jpg"},

    {name:"双截龙2.nes",desc:"双截龙2",img:"default.jpg"},
    {name:"双截龙3.nes",desc:"双截龙3",img:"default.jpg"},
    {name:"1943.nes",desc:"1943",img:"default.jpg"},

    {name:"泡泡龙.nes",desc:"泡泡龙",img:"default.jpg"},
    {name:"泡泡龙2.nes",desc:"泡泡龙2",img:"default.jpg"},

    // {name:"AV麻将.nes",desc:"AV麻将",img:"default.jpg"},
    // {name:"F1赛车.nes",desc:"F1赛车",img:"default.jpg"},
    {name:"FC原人.nes",desc:"FC原人",img:"default.jpg"},

    // {name:"七宝奇谋.nes",desc:"七宝奇谋",img:"default.jpg"},
    {name:"三只小猪.nes",desc:"三只小猪",img:"default.jpg"},
    {name:"三目童子.nes",desc:"三目童子",img:"default.jpg"},
    {name:"中东战争.nes",desc:"中东战争",img:"default.jpg"},
    {name:"中华大仙.nes",desc:"中华大仙",img:"default.jpg"},
    {name:"中国象棋.nes",desc:"中国象棋",img:"default.jpg"},
    {name:"人间兵器.nes",desc:"人间兵器",img:"default.jpg"},
    {name:"企鹅梦物语.nes",desc:"企鹅梦物语",img:"default.jpg"},
    {name:"俄罗斯方块.nes",desc:"俄罗斯方块",img:"default.jpg"},
    {name:"充气狗.nes",desc:"充气狗",img:"default.jpg"},
    {name:"兵蜂.nes",desc:"兵蜂",img:"default.jpg"},
    {name:"功夫.nes",desc:"功夫",img:"default.jpg"},
    // {name:"加纳战机(无限命+无限雷 hack by 小粽子).nes",desc:"加纳战机无限命无限雷",img:"default.jpg"},
    // {name:"加纳战机.nes",desc:"加纳战机",img:"default.jpg"},
    // {name:"南京企鹅.nes",desc:"南京企鹅",img:"default.jpg"},


    {name:"吃豆.nes",desc:"吃豆",img:"default.jpg"},
    {name:"唐老鸭梦冒险.nes",desc:"唐老鸭梦冒险",img:"default.jpg"},
    {name:"唐老鸭梦冒险2.nes",desc:"唐老鸭梦冒险2",img:"default.jpg"},
    {name:"嘉蒂外传.nes",desc:"嘉蒂外传",img:"default.jpg"},
    {name:"地底探险.nes",desc:"地底探险",img:"default.jpg"},

    {name:"外星战将.nes",desc:"外星战将",img:"default.jpg"},
    // {name:"小蜜蜂.nes",desc:"小蜜蜂",img:"default.jpg"},
    {name:"彩虹岛.nes",desc:"彩虹岛",img:"default.jpg"},
    {name:"影子传说.nes",desc:"影子传说",img:"default.jpg"},
    {name:"影子传说（无敌版）by nianxu.nes",desc:"影子传说无敌版",img:"default.jpg"},
    {name:"忍者神龟2.nes",desc:"忍者神龟2",img:"default.jpg"},
    // {name:"忍者神龟3.nes",desc:"忍者神龟3",img:"default.jpg"},
    {name:"忍者蛙.nes",desc:"忍者蛙",img:"default.jpg"},
    {name:"忍者龙剑传1.nes",desc:"忍者龙剑传1",img:"default.jpg"},
    {name:"忍者龙剑传2.nes",desc:"忍者龙剑传2",img:"default.jpg"},
    {name:"忍者龙剑传3.nes",desc:"忍者龙剑传3",img:"default.jpg"},
    {name:"快乐猫.nes",desc:"快乐猫",img:"default.jpg"},
    {name:"快打旋风 [老代汉化].nes",desc:"快打旋风汉化",img:"default.jpg"},
    {name:"快打旋风.nes",desc:"快打旋风",img:"default.jpg"},
    {name:"怪鸭历险.nes",desc:"怪鸭历险",img:"default.jpg"},
    {name:"恶魔城.nes",desc:"恶魔城",img:"default.jpg"},
    {name:"成龙之龙.nes",desc:"成龙之龙",img:"default.jpg"},
    {name:"拆屋工.nes",desc:"拆屋工",img:"default.jpg"},
    // {name:"摩托车大赛.nes",desc:"摩托车大赛",img:"default.jpg"},
    {name:"敲冰块.nes",desc:"敲冰块",img:"default.jpg"},
    {name:"最终任务.nes",desc:"最终任务",img:"default.jpg"},
    {name:"未来战士.nes",desc:"未来战士",img:"default.jpg"},

    // {name:"柯拉米世界2.nes",desc:"柯拉米世界2",img:"default.jpg"},
    // {name:"桌球.nes",desc:"桌球",img:"default.jpg"},
    // {name:"沙罗曼蛇.nes",desc:"沙罗曼蛇",img:"default.jpg"},

    {name:"激龟快打.nes",desc:"激龟快打",img:"default.jpg"},
    {name:"火之鸟.nes",desc:"火之鸟",img:"default.jpg"},
    {name:"火箭车.nes",desc:"火箭车",img:"default.jpg"},
    {name:"炸弹人.nes",desc:"炸弹人",img:"default.jpg"},
    {name:"热血格斗传说.nes",desc:"热血格斗传说",img:"default.jpg"},
    {name:"特救指令.nes",desc:"特救指令",img:"default.jpg"},
    // {name:"王子外传.nes",desc:"王子外传",img:"default.jpg"},
    {name:"究极虎.nes",desc:"究极虎",img:"default.jpg"},
    {name:"绿色兵团.nes",desc:"绿色兵团",img:"default.jpg"},
    {name:"脱狱.nes",desc:"脱狱",img:"default.jpg"},
    {name:"脱狱2.nes",desc:"脱狱2",img:"default.jpg"},
    {name:"荒野大镖客.nes",desc:"荒野大镖客",img:"default.jpg"},
    {name:"菲力猫.nes",desc:"菲力猫",img:"default.jpg"},
    // {name:"蝙蝠侠.nes",desc:"蝙蝠侠",img:"default.jpg"},
    {name:"西游记.nes",desc:"西游记",img:"default.jpg"},
    {name:"赤影战士.nes",desc:"赤影战士",img:"default.jpg"},
    // {name:"赤色要塞.nes",desc:"赤色要塞",img:"default.jpg"},

    {name:"越野机车.nes",desc:"越野机车",img:"default.jpg"},
    {name:"踢王.nes",desc:"踢王",img:"default.jpg"},
    {name:"顽皮狗.nes",desc:"顽皮狗",img:"default.jpg"},
    {name:"马戏团.nes",desc:"马戏团",img:"default.jpg"},

    {name:"魔鬼总动员.nes",desc:"魔鬼总动员",img:"default.jpg"},
    {name:"鳄鱼先生.nes",desc:"鳄鱼先生",img:"default.jpg"},
    {name:"鸟人战队.nes",desc:"鸟人战队",img:"default.jpg"},
    // {name:"魂斗罗.nes",desc:"魂斗罗",img:"default.jpg"},
    {name:"筋肉人[Madcell汉化].nes",desc:"筋肉人-摔角大赛",img:"default.jpg"},
    {name:"救火英雄[cslrxyz汉化].nes",desc:"救火英雄",img:"default.jpg"},
    {name:"口袋妖怪四合一[火星电子].NES",desc:"口袋妖怪",img:"default.jpg"}
]